"""Freeze the evidence: sha256-hash every CSV/JSON under results/.

Writes results/EVIDENCE_SHA256.txt — a tamper-evident manifest of the
measured result files. Re-run after any results change; the file itself is
committed so hashes are public and checkable.

Run: PYTHONPATH=. python3 scripts/freeze_evidence.py
"""

import hashlib
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
RESULTS = os.path.join(ROOT, "results")
OUT = os.path.join(RESULTS, "EVIDENCE_SHA256.txt")


def main():
    entries = []
    for dirpath, _dirnames, filenames in os.walk(RESULTS):
        for fn in sorted(filenames):
            if fn == "EVIDENCE_SHA256.txt":
                continue
            if not fn.endswith((".csv", ".json")):
                continue
            path = os.path.join(dirpath, fn)
            h = hashlib.sha256()
            with open(path, "rb") as f:
                for chunk in iter(lambda: f.read(1 << 20), b""):
                    h.update(chunk)
            rel = os.path.relpath(path, ROOT)
            entries.append((rel, h.hexdigest()))
    entries.sort()
    with open(OUT, "w") as f:
        f.write("# Frozen evidence manifest — sha256 of measured result files.\n")
        f.write("# Re-generated by scripts/freeze_evidence.py; do not hand-edit.\n")
        for rel, digest in entries:
            f.write(f"{digest}  {rel}\n")
    print(f"wrote {OUT}: {len(entries)} files hashed")


if __name__ == "__main__":
    main()
